export const ROOT = '/'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const USER_DESHBOARD = '/user/deshboard'
export const SHOP = '/shop'
export const CART = '/user/cart'
export const LOGOUT = '/user/logout'
